site_name: Profilis
repo_url: https://github.com/ankan97dutta/profilis
theme:
  name: material
  logo: assets/logo.svg      # your custom SVG
  favicon: assets/favicon.svg  # optional
  palette:
    - scheme: default
      primary: custom
      accent: custom
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - search.suggest
    - content.code.copy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: true
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
  - mermaid2
nav:
  - Home: index.md
  - Overview:
      - Problem: overview/problem-statement.md
      - Roadmap: overview/roadmap.md
  - Architecture:
      - Architecture: architecture/architecture.md
  - Guides:
      - Getting started: guides/getting-started.md
      - Configuration: guides/configuration.md
      - Installation: guides/installation.md
  - Adapters:
      - Flask: adapters/flask.md
      - FastAPI: adapters/fastapi.md
  - Databases:
      - SQLAlchemy: databases/sqlalchemy.md
  - Exporters:
      - JSONL: exporters/jsonl.md
  - UI:
      - UI: ui/ui.md
  - Meta:
      - Contributing: meta/contributing.md
      - Dev guidelines: meta/development-guidelines.md
      - Code of Conduct: meta/code-of-conduct.md
