site_name: Profilis
repo_url: https://github.com/ankan97dutta/profilis
theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed
  - attr_list
  - md_in_html
plugins:
  - search
  - mermaid2
nav:
  - Home: index.md
  - Overview:
      - Problem: overview/problem-statement.md
      - Roadmap: overview/roadmap.md
  - Architecture:
      - Architecture: architecture/architecture.md
  - Guides:
      - Getting started: guides/getting-started.md
      - Configuration: guides/configuration.md
      - Installation: guides/installation.md
  - Adapters:
      - Flask: adapters/flask.md
      - FastAPI: adapters/fastapi.md
  - Databases:
      - SQLAlchemy: databases/sqlalchemy.md
  - Exporters:
      - JSONL: exporters/jsonl.md
  - UI:
      - UI: ui/ui.md
  - Meta:
      - Contributing: meta/contributing.md
      - Dev guidelines: meta/development-guidelines.md
      - Code of Conduct: meta/code-of-conduct.md
